### ISSUE TITLE
Instalation Failed

### ISSUE THREAD

**Issue by isaiahaguilera** [aymanizz/Brackets-Build-Systems#1]
Upon installing the extension I get installation failed screen and I am unable to use the tool.  When looking at dev tools for brackets I see this error related to your extension.

TypeError: Cannot call method 'setChecked' of undefined

Not sure this is a bug or something I did.  Thanks

**Comment by aymanizz** [comment]
that's strange! but another version will be released soon, maybe next week, so I hope you wait till it's released and check if the error occurs again, thanks for opening the issue I will keep it open.

**Comment by tylerdmace** [comment]
I get an extension error during installation through the Brackets Extension Manager:

Installation failed. The extension encountered an error while starting up.

**Comment by blorkfish** [comment]
I had the same issues as above.
I did manage to install using a zip file from your commit on July 9, 2014.

**Comment by aymanizz** [comment]
fixed issue and updated extension to version 1.0.2, please before installing do the following :
1. Remove old extension.
2. Delete all preferences related to the extension (`Debug > Open Preferences File`).
3. install the newest version of the extension.

I hope this fixes the issue. If it does,  please report.
