### ISSUE TITLE
Paths do not resolve properly on Windows.

### ISSUE THREAD

**Issue by 5310** [aymanizz/Brackets-Build-Systems#2]
I've been trying to set-up custom commands to run on Windows, but so far I've been unable to get paths to resolve properly.
- Paths with spaces must be quoted to work on Windows command-line.
- Windows does not understand single-quote delimited paths.
- JSON files cannot contain single-quote delimited string, therefor I cannot swtch these around.
- Escaping double-quotes in JSON doesn't work either as the command seems to be ran with the escape backslashes.
- Furthermore, since Windows file paths use backslashes, simply invoking any build commands fail with the error `Invalid switch - "users"` as the project path uses forward slashes `C:/Users/User/Desktop/`. 
- And I cannot escape backslashes either as both of them are sent to the command line.
- And even if I could, I cannot change the variables which contain paths with forward slashes.

I see that the addon has been tested on Windows 7. I am on Windwos 8.1, and have not tried this on 7. Could this be an issue? Can this be otherwise averted?

**Comment by lepinay** [comment]
Did you find a work around this ?
