### ISSUE TITLE
brackets build system is not working

### ISSUE THREAD

**Issue by misutkame** [aymanizz/Brackets-Build-Systems#4]
nothing happens when build command is run for the following config
{
    "name": "node version",
    "dir": "$PROJECT_ROOT",
    "cmd": "node -v"
  },

**Comment by veke** [comment]
Confirmed. OSX Maverics. This plugin does nothing.
Also the Build menu context is not responding when clicked, time to time.

**Comment by niedzwiedzislaw** [comment]
On windows 8 nothing at all works.

**Comment by aymanizz** [comment]
Sorry for late response. Anyway, the extension is built using the old API so it doesn't work properly on new versions of brackets and therefore on any platform.
I'm not sure whether I'll have time to renew it or not, but I will try to free some time and work on it soon.
